##### Write a function so that the columns of the output matrix are powers of the input vector.
##### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
##### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
#import numpy library
import numpy as np

In [2]:
#initialize 1-D array
arr=np.array([2,2,3,4])

In [3]:
#Initialize no of columns in N
N=4

In [4]:
#Function to implement the vander matrix logic
#Function which takes input as a array or Vector and N.

def gen_vander_matrix(inputvector, N, increasing=False):
    
    if not increasing:
        out_mat = np.array([x**(N-1-i) for x in inputvector for i in range(N)]).reshape(len(inputvector),N)
    elif increasing:
        out_mat = np.array([x**i for x in inputvector for i in range(N)]).reshape(len(inputvector),N)
    
    return out_mat

inputvector=np.array([1,2,3,4,5])
N=3

print("=================output when increasing set to False==============")
print(gen_vander_matrix(inputvector,N))

print("===================Ouput when increasing set to True==============")
print(gen_vander_matrix(inputvector,N, True))

=================output when increasing set to False==============
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
===================Ouput when increasing set to True==============
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


##### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
#Function to find moving average of a sequence.
#FUnction takes seq as input array and window_size
def moving_avg(inp_arr,win_size):
    
    #Initialize an empty array
    emp_arr=np.array([])
    #Find the no of values based on the formula (n-k+1)
    #where n is legnth of seq and k is window size
    val=len(inp_arr)-win_size+1
    
    #For loop to iterate for the range(val)
    for i in range(val):
        emp_arr=np.append(emp_arr, sum(np.array(inp_arr[:win_size]))/win_size)
        inp_arr=np.delete(inp_arr,0)
    return emp_arr

seq=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_avg(seq,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])